/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Organization1RouteImport } from './routes/organization1'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as Dashboard1RouteImport } from './routes/dashboard1'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AdminCreateUserRouteImport } from './routes/admin/create-user'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as OrganizationSlugDashboardRouteImport } from './routes/organization/$slug/dashboard'
import { Route as OrganizationSlugPathRouteImport } from './routes/organization/$slug/$path'
import { Route as ApiOrganizationCreateRouteImport } from './routes/api/organization/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardSomethingRouteImport } from './routes/_protected/dashboard/something'
import { Route as ProtectedDashboardMachinesIndexRouteImport } from './routes/_protected/dashboard/machines/index'
import { Route as ProtectedDashboardLocationsIndexRouteImport } from './routes/_protected/dashboard/locations/index'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Organization1Route = Organization1RouteImport.update({
  id: '/organization1',
  path: '/organization1',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard1Route = Dashboard1RouteImport.update({
  id: '/dashboard1',
  path: '/dashboard1',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/admin/create-user',
  path: '/admin/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const OrganizationSlugDashboardRoute =
  OrganizationSlugDashboardRouteImport.update({
    id: '/organization/$slug/dashboard',
    path: '/organization/$slug/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationSlugPathRoute = OrganizationSlugPathRouteImport.update({
  id: '/organization/$slug/$path',
  path: '/organization/$slug/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationCreateRoute = ApiOrganizationCreateRouteImport.update({
  id: '/api/organization/create',
  path: '/api/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardSomethingRoute =
  ProtectedDashboardSomethingRouteImport.update({
    id: '/something',
    path: '/something',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMachinesIndexRoute =
  ProtectedDashboardMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardLocationsIndexRoute =
  ProtectedDashboardLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard1': typeof Dashboard1Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization/': typeof OrganizationIndexRoute
  '/dashboard/something': typeof ProtectedDashboardSomethingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
  '/dashboard/locations/': typeof ProtectedDashboardLocationsIndexRoute
  '/dashboard/machines/': typeof ProtectedDashboardMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard1': typeof Dashboard1Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization': typeof OrganizationIndexRoute
  '/dashboard/something': typeof ProtectedDashboardSomethingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
  '/dashboard/locations': typeof ProtectedDashboardLocationsIndexRoute
  '/dashboard/machines': typeof ProtectedDashboardMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/dashboard1': typeof Dashboard1Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization/': typeof OrganizationIndexRoute
  '/_protected/dashboard/something': typeof ProtectedDashboardSomethingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
  '/_protected/dashboard/locations/': typeof ProtectedDashboardLocationsIndexRoute
  '/_protected/dashboard/machines/': typeof ProtectedDashboardMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard1'
    | '/forgot-password'
    | '/login'
    | '/organization1'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/dashboard'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization/'
    | '/dashboard/something'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
    | '/dashboard/locations/'
    | '/dashboard/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard1'
    | '/forgot-password'
    | '/login'
    | '/organization1'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/dashboard'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization'
    | '/dashboard/something'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
    | '/dashboard/locations'
    | '/dashboard/machines'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/dashboard1'
    | '/forgot-password'
    | '/login'
    | '/organization1'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/_protected/dashboard'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization/'
    | '/_protected/dashboard/something'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
    | '/_protected/dashboard/locations/'
    | '/_protected/dashboard/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  Dashboard1Route: typeof Dashboard1Route
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  Organization1Route: typeof Organization1Route
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UserRoute: typeof UserRoute
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrganizationCreateRoute: typeof ApiOrganizationCreateRoute
  OrganizationSlugPathRoute: typeof OrganizationSlugPathRoute
  OrganizationSlugDashboardRoute: typeof OrganizationSlugDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization1': {
      id: '/organization1'
      path: '/organization1'
      fullPath: '/organization1'
      preLoaderRoute: typeof Organization1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard1': {
      id: '/dashboard1'
      path: '/dashboard1'
      fullPath: '/dashboard1'
      preLoaderRoute: typeof Dashboard1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/organization/$slug/dashboard': {
      id: '/organization/$slug/dashboard'
      path: '/organization/$slug/dashboard'
      fullPath: '/organization/$slug/dashboard'
      preLoaderRoute: typeof OrganizationSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$slug/$path': {
      id: '/organization/$slug/$path'
      path: '/organization/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof OrganizationSlugPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/create': {
      id: '/api/organization/create'
      path: '/api/organization/create'
      fullPath: '/api/organization/create'
      preLoaderRoute: typeof ApiOrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/something': {
      id: '/_protected/dashboard/something'
      path: '/something'
      fullPath: '/dashboard/something'
      preLoaderRoute: typeof ProtectedDashboardSomethingRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/machines/': {
      id: '/_protected/dashboard/machines/'
      path: '/machines'
      fullPath: '/dashboard/machines/'
      preLoaderRoute: typeof ProtectedDashboardMachinesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/locations/': {
      id: '/_protected/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof ProtectedDashboardLocationsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardSomethingRoute: typeof ProtectedDashboardSomethingRoute
  ProtectedDashboardLocationsIndexRoute: typeof ProtectedDashboardLocationsIndexRoute
  ProtectedDashboardMachinesIndexRoute: typeof ProtectedDashboardMachinesIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardSomethingRoute: ProtectedDashboardSomethingRoute,
  ProtectedDashboardLocationsIndexRoute: ProtectedDashboardLocationsIndexRoute,
  ProtectedDashboardMachinesIndexRoute: ProtectedDashboardMachinesIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  Dashboard1Route: Dashboard1Route,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  Organization1Route: Organization1Route,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UserRoute: UserRoute,
  AdminCreateUserRoute: AdminCreateUserRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrganizationCreateRoute: ApiOrganizationCreateRoute,
  OrganizationSlugPathRoute: OrganizationSlugPathRoute,
  OrganizationSlugDashboardRoute: OrganizationSlugDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
