/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as Organization1RouteImport } from './routes/organization1'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Dashboard1RouteImport } from './routes/dashboard1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AdminCreateUserRouteImport } from './routes/admin/create-user'
import { Route as OrganizationSlugDashboardRouteImport } from './routes/organization/$slug/dashboard'
import { Route as OrganizationSlugPathRouteImport } from './routes/organization/$slug/$path'
import { Route as ApiOrganizationCreateRouteImport } from './routes/api/organization/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const Organization1Route = Organization1RouteImport.update({
  id: '/organization1',
  path: '/organization1',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard1Route = Dashboard1RouteImport.update({
  id: '/dashboard1',
  path: '/dashboard1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/admin/create-user',
  path: '/admin/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugDashboardRoute =
  OrganizationSlugDashboardRouteImport.update({
    id: '/organization/$slug/dashboard',
    path: '/organization/$slug/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationSlugPathRoute = OrganizationSlugPathRouteImport.update({
  id: '/organization/$slug/$path',
  path: '/organization/$slug/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationCreateRoute = ApiOrganizationCreateRouteImport.update({
  id: '/api/organization/create',
  path: '/api/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard1': typeof Dashboard1Route
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/user': typeof UserRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard1': typeof Dashboard1Route
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/user': typeof UserRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/dashboard': typeof DashboardIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard1': typeof Dashboard1Route
  '/login': typeof LoginRoute
  '/organization1': typeof Organization1Route
  '/user': typeof UserRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
  '/organization/$slug/dashboard': typeof OrganizationSlugDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard1'
    | '/login'
    | '/organization1'
    | '/user'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/dashboard/'
    | '/organization/'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard1'
    | '/login'
    | '/organization1'
    | '/user'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/dashboard'
    | '/organization'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard1'
    | '/login'
    | '/organization1'
    | '/user'
    | '/admin/create-user'
    | '/auth/$path'
    | '/settings/$path'
    | '/dashboard/'
    | '/organization/'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
    | '/organization/$slug/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard1Route: typeof Dashboard1Route
  LoginRoute: typeof LoginRoute
  Organization1Route: typeof Organization1Route
  UserRoute: typeof UserRoute
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrganizationCreateRoute: typeof ApiOrganizationCreateRoute
  OrganizationSlugPathRoute: typeof OrganizationSlugPathRoute
  OrganizationSlugDashboardRoute: typeof OrganizationSlugDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization1': {
      id: '/organization1'
      path: '/organization1'
      fullPath: '/organization1'
      preLoaderRoute: typeof Organization1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard1': {
      id: '/dashboard1'
      path: '/dashboard1'
      fullPath: '/dashboard1'
      preLoaderRoute: typeof Dashboard1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$slug/dashboard': {
      id: '/organization/$slug/dashboard'
      path: '/organization/$slug/dashboard'
      fullPath: '/organization/$slug/dashboard'
      preLoaderRoute: typeof OrganizationSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$slug/$path': {
      id: '/organization/$slug/$path'
      path: '/organization/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof OrganizationSlugPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/create': {
      id: '/api/organization/create'
      path: '/api/organization/create'
      fullPath: '/api/organization/create'
      preLoaderRoute: typeof ApiOrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard1Route: Dashboard1Route,
  LoginRoute: LoginRoute,
  Organization1Route: Organization1Route,
  UserRoute: UserRoute,
  AdminCreateUserRoute: AdminCreateUserRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrganizationCreateRoute: ApiOrganizationCreateRoute,
  OrganizationSlugPathRoute: OrganizationSlugPathRoute,
  OrganizationSlugDashboardRoute: OrganizationSlugDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
