/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as OrganizationSlugPathRouteImport } from './routes/organization/$slug/$path'
import { Route as ApiOrganizationCreateRouteImport } from './routes/api/organization/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugPathRoute = OrganizationSlugPathRouteImport.update({
  id: '/$slug/$path',
  path: '/$slug/$path',
  getParentRoute: () => OrganizationRoute,
} as any)
const ApiOrganizationCreateRoute = ApiOrganizationCreateRouteImport.update({
  id: '/api/organization/create',
  path: '/api/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/user': typeof UserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/user': typeof UserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/user': typeof UserRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/organization/create': typeof ApiOrganizationCreateRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/organization'
    | '/user'
    | '/auth/$path'
    | '/settings/$path'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/organization'
    | '/user'
    | '/auth/$path'
    | '/settings/$path'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/organization'
    | '/user'
    | '/auth/$path'
    | '/settings/$path'
    | '/api/auth/$'
    | '/api/organization/create'
    | '/organization/$slug/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
  UserRoute: typeof UserRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrganizationCreateRoute: typeof ApiOrganizationCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$slug/$path': {
      id: '/organization/$slug/$path'
      path: '/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof OrganizationSlugPathRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/api/organization/create': {
      id: '/api/organization/create'
      path: '/api/organization/create'
      fullPath: '/api/organization/create'
      preLoaderRoute: typeof ApiOrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizationRouteChildren {
  OrganizationSlugPathRoute: typeof OrganizationSlugPathRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationSlugPathRoute: OrganizationSlugPathRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
  UserRoute: UserRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrganizationCreateRoute: ApiOrganizationCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
